### ISSUE TITLE
DB start fail if default timeout 1m30sec exeeded on CentOS7

### ISSUE THREAD

**Issue by DmitriyStoyanov** [lean-delivery/ansible-role-oracle-db#11]
##### SUMMARY

We found, that if database start will be longer than 1m30sec, listener will be stopped and during server shutdown database will be stopped accidentally.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```

```

##### OS / ENVIRONMENT

CentOS7

##### STEPS TO REPRODUCE

Database with long start

```yaml

```

##### EXPECTED RESULTS

Default timeout should be increased

For example i have fixed by increasing timeout to 5min adding here templates\oracledb.systemd.j2

[Service]
...
TimeoutSec=300

##### ACTUAL RESULTS

```

```

**Comment by tgadiev** [comment]
Closed as pull request https://github.com/lean-delivery/ansible-role-oracle-db/pull/13 merged
